import { YosenAccordionProps } from '@/templates/accordion/YosenAccordion'

export const edoEvents: YosenAccordionProps[] = [
  {
    cName: 'edo',
    title: '其の一',
    date: '2026年5月9日（土）',
    open: '17:00',
    start: '17:20',
    place: 'GOTANDA G7',
    artists:
      "ADMIRAL×BANQUET／Harley Queen／Re:M!ND／ラビットビット／オトメルキュール／I's Merry Go Round／MiDi ON!／@youuuuu!!!／New Crown",
    ticket: 'https://t-dv.com/yosen_edo_1',
    image1: 'https://sekigahara-idolwars.net/2026/yosen/edo/11.jpg',
    image2: 'https://sekigahara-idolwars.net/2026/yosen/edo/12.jpg',
  },
  {
    cName: 'edo',
    title: '其の二',
    date: '2026年5月10日（日）',
    open: '11:30',
    start: '12:00',
    place: 'シアターマーキュリー新宿',
    artists: 'Coloration／ヒップバーン／オトメルキュール／vVibe!／あもるてぃえ／LEVEL7／MiDi ON!',
    ticket: 'https://t-dv.com/yosen_edo_2',
    image1: 'https://sekigahara-idolwars.net/2026/yosen/edo/21.jpg',
    image2: 'https://sekigahara-idolwars.net/2026/yosen/edo/22.jpg',
  },
  {
    cName: 'edo',
    title: '其の三',
    date: '2026年5月10日（日）',
    open: '17:00',
    start: '17:30',
    place: 'シアターマーキュリー新宿',
    artists:
      "Aproof／Coloration／iROTORiDOLLY／ラビットビット／vVibe!／LEVEL7／I's Merry Go Round／BabyDoll",
    ticket: 'https://t-dv.com/yosen_edo_3',
    image1: 'https://sekigahara-idolwars.net/2026/yosen/edo/31.jpg',
    image2: 'https://sekigahara-idolwars.net/2026/yosen/edo/32.jpg',
  },
  {
    cName: 'edo',
    title: '其の四',
    date: '2026年5月10日（日）',
    open: '11:00',
    start: '11:30',
    place: '浅草花劇場',
    artists: 'Yo2La／BrainBeat／melnoir／Otomeria／NEOTOKYO-TRIBE',
    ticket: 'https://t-dv.com/yosen_edo_4',
    image1: 'https://sekigahara-idolwars.net/2026/yosen/edo/41.jpg',
    image2: 'https://sekigahara-idolwars.net/2026/yosen/edo/42.jpg',
  },
  {
    cName: 'edo',
    title: '其の五',
    date: '2026年5月10日（日）',
    open: '16:00',
    start: '16:30',
    place: '浅草花劇場',
    artists:
      'にとくり。／ひとつキラリ／ADMIRAL×BANQUET／ゆにきゅーと／ヒップバーン／オトメルキュール／Otomeria／あもるてぃえ／NEOTOKYO-TRIBE／MiDi ON!',
    ticket: 'https://t-dv.com/yosen_edo_5',
    image1: 'https://sekigahara-idolwars.net/2026/yosen/edo/51.jpg',
    image2: 'https://sekigahara-idolwars.net/2026/yosen/edo/52.jpg',
  },
  {
    cName: 'edo',
    title: '其の六',
    date: '2026年5月14日（木）',
    open: '17:30',
    start: '18:00',
    place: 'シアターマーキュリー新宿',
    artists:
      'Aproof／にとくり。／ひとつキラリ／Coloration／ゆにきゅーと／ラビットビット／オトメルキュール／BLUE REGRET。／NEOTOKYO-TRIBE／New Crown',
    ticket: 'https://t-dv.com/yosen_edo_6',
    image1: 'https://sekigahara-idolwars.net/2026/yosen/edo/61.jpg',
  },
  {
    cName: 'edo',
    title: '其の七',
    date: '2026年5月17日（日）',
    open: '11:15',
    start: '11:30',
    place: 'シアターマーキュリー新宿',
    artists:
      'にとくり。／ひとつキラリ／BrainBeat／ヒップバーン／melnoir／vVibe!／Chuu♡Cute／INOiZe↯／NEOTOKYO-TRIBE／New Crown',
    ticket: 'https://t-dv.com/yosen_edo_7',
    image1: 'https://sekigahara-idolwars.net/2026/yosen/edo/71.jpg',
  },
  {
    cName: 'edo',
    title: '其の八',
    date: '2026年5月17日（日）',
    open: '16:00',
    start: '16:20',
    place: 'シアターマーキュリー新宿',
    artists:
      "Aproof／ADMIRAL×BANQUET／Coloration／BrainBeat／ゆにきゅーと／ラビットビット／BLUE REGRET。／vVibe!／FIRST DREAM／Chuu♡Cute／LEVEL7／NEOTOKYO-TRIBE／I's Merry Go Round／@youuuuu!!!／BabyDoll／New Crown",
    ticket: 'https://t-dv.com/yosen_edo_8',
    image1: 'https://sekigahara-idolwars.net/2026/yosen/edo/81.jpg',
  },
  {
    cName: 'edo',
    title: '其の九',
    date: '2026年5月21日（木）',
    open: '17:30',
    start: '18:00',
    place: 'シアターマーキュリー新宿',
    artists:
      'Aproof／ADMIRAL×BANQUET／Yo2La／Coloration／ラビットビット／オトメルキュール／Otomeria／「いつかのネバーランド」／FIRST DREAM／LEVEL7',
    ticket: 'https://t-dv.com/yosen_edo_9',
    image1: 'https://sekigahara-idolwars.net/2026/yosen/edo/91.jpg',
  },
  {
    cName: 'edo',
    title: '其の十',
    date: '2026年5月23日（土）',
    open: '10:40',
    start: '11:00',
    place: '浅草花劇場',
    artists: 'ADMIRAL×BANQUET／Yo2La／あもるてぃえ／NEOTOKYO-TRIBE／@youuuuu!!!／BabyDoll',
    ticket: 'https://t-dv.com/yosen_edo_10',
    image1: 'https://sekigahara-idolwars.net/2026/yosen/edo/101.jpg',
  },
  {
    cName: 'edo',
    title: '其の十一',
    date: '2026年5月23日（土）',
    open: '15:00',
    start: '15:20',
    place: '浅草花劇場',
    artists:
      "にとくり。／ひとつキラリ／Re:M!ND／ゆにきゅーと／ヒップバーン／melnoir／オトメルキュール／Otomeria／あもるてぃえ／ギミラブ！／I's Merry Go Round／New Crown",
    ticket: 'https://t-dv.com/yosen_edo_11',
    image1: 'https://sekigahara-idolwars.net/2026/yosen/edo/111.jpg',
  },
  {
    cName: 'edo',
    title: '其の十二',
    date: '2026年5月24日（日）',
    open: '11:15',
    start: '11:30',
    place: 'シアターマーキュリー新宿',
    artists:
      'にとくり。／ひとつキラリ／ゆにきゅーと／ヒップバーン／LEVEL7／BabyDoll／NEOTOKYO-TRIBE',
    ticket: 'https://t-dv.com/yosen_edo_12',
    image1: 'https://sekigahara-idolwars.net/2026/yosen/edo/121.jpg',
  },
  {
    cName: 'edo',
    title: '其の十三',
    date: '2026年5月24日（日）',
    open: '16:00',
    start: '16:15',
    place: 'シアターマーキュリー新宿',
    artists:
      "BrainBeat／melnoir／オトメルキュール／vVibe!／Otomeria／「いつかのネバーランド」／あもるてぃえ／LEVEL7／ギミラブ！／I's Merry Go Round／MiDi ON!",
    ticket: 'https://t-dv.com/yosen_edo_13',
    image1: 'https://sekigahara-idolwars.net/2026/yosen/edo/131.jpg',
  },
  {
    cName: 'edo',
    title: '其の十四',
    date: '2026年5月25日（月）',
    open: '16:00',
    start: '16:30',
    place: '新宿ReNY',
    artists:
      'Yo2La／BrainBeat／ゆにきゅーと／ラビットビット／ヒップバーン／BLUE REGRET。／Otomeria／「いつかのネバーランド」／INOiZe↯／LEVEL7／@youuuuu!!!／New Crown',
    ticket: 'https://t-dv.com/yosen_edo_14',
    image1: 'https://sekigahara-idolwars.net/2026/yosen/edo/141.jpg',
  },
  {
    cName: 'edo',
    title: '其の十五',
    date: '2026年5月27日（水）',
    open: '17:30',
    start: '18:00',
    place: 'シアターマーキュリー新宿',
    artists:
      'にとくり。／ひとつキラリ／BrainBeat／vVibe!／Otomeria／Chuu♡Cute／あもるてぃえ／New Crown',
    ticket: 'https://t-dv.com/yosen_edo_15',
    image1: 'https://sekigahara-idolwars.net/2026/yosen/edo/151.jpg',
  },
  {
    cName: 'edo',
    title: '其の十六',
    date: '2026年5月28日（木）',
    open: '17:30',
    start: '18:00',
    place: 'シアターマーキュリー新宿',
    artists:
      'にとくり。／ひとつキラリ／ADMIRAL×BANQUET／Yo2La／Coloration／BrainBeat／ゆにきゅーと／ヒップバーン／BLUE REGRET。',
    ticket: 'https://t-dv.com/yosen_edo_16',
    image1: 'https://sekigahara-idolwars.net/2026/yosen/edo/161.jpg',
  },
]
