import { YosenAccordionProps } from '@/templates/accordion/YosenAccordion'

export const osakaEvents: YosenAccordionProps[] = [
  {
    cName: 'osaka',
    title: '其の一',
    date: '2026年5月9日（土）',
    open: '11:00',
    start: '11:30',
    place: '大阪・京橋Arc',
    artists:
      'anemoreel／めろでぃらびっと／Squall Line／わんみゅーず！／SANUGLOW／キューハチパーセント！／Mihiro／プラチナリボン',
    ticket: 'https://t-dv.com/yosen_osaka_1',
    image1: 'https://sekigahara-idolwars.net/2026/yosen/osaka/11.jpg',
    image2: 'https://sekigahara-idolwars.net/2026/yosen/osaka/12.jpg',
  },
  {
    cName: 'osaka',
    title: '其の二',
    date: '2026年5月9日（土）',
    open: '17:00',
    start: '17:30',
    place: '大阪・京橋Arc',
    artists:
      'anemoreel／めろでぃらびっと／Squall Line／SANUGLOW／Lumi Prima／キューハチパーセント！／HIGH SPY DOLL／tune time capsule／Mihiro',
    ticket: 'https://t-dv.com/yosen_osaka_2',
    image1: 'https://sekigahara-idolwars.net/2026/yosen/osaka/21.jpg',
    image2: 'https://sekigahara-idolwars.net/2026/yosen/osaka/22.jpg',
  },
  {
    cName: 'osaka',
    title: '其の三',
    date: '2026年5月16日（土）',
    open: '11:30',
    start: '12:00',
    place: '大阪・京橋Arc',
    artists: 'anemoreel／めろでぃらびっと／Squall Line／Nody／わんみゅーず！／SANUGLOW／Mihiro',
    ticket: 'https://t-dv.com/yosen_osaka_3',
    image1: 'https://sekigahara-idolwars.net/2026/yosen/osaka/31.jpg',
    image2: 'https://sekigahara-idolwars.net/2026/yosen/osaka/32.jpg',
  },
  {
    cName: 'osaka',
    title: '其の四',
    date: '2026年5月16日（土）',
    open: '17:30',
    start: '18:00',
    place: '大阪・京橋Arc',
    artists:
      'anemoreel／めろでぃらびっと／Squall Line／Nody／Lumi Prima／HIGH SPY DOLL／Mihiro／プラチナリボン',
    ticket: 'https://t-dv.com/yosen_osaka_4',
    image1: 'https://sekigahara-idolwars.net/2026/yosen/osaka/41.jpg',
  },
  {
    cName: 'osaka',
    title: '其の五',
    date: '2026年5月17日（日）',
    open: '11:00',
    start: '11:30',
    place: '大阪・京橋Arc',
    artists:
      "anemoreel／めろでぃらびっと／IDOL★ST∀R MINE／わんみゅーず！／SANUGLOW／Lumi Prima／image／colorin'c／プラチナリボン",
    ticket: 'https://t-dv.com/yosen_osaka_5',
    image1: 'https://sekigahara-idolwars.net/2026/yosen/osaka/51.jpg',
  },
  {
    cName: 'osaka',
    title: '其の六',
    date: '2026年5月17日（日）',
    open: '17:00',
    start: '17:30',
    place: '大阪・京橋Arc',
    artists:
      "anemoreel／めろでぃらびっと／IDOL★ST∀R MINE／SANUGLOW／Lumi Prima／image／キューハチパーセント！／colorin'c／HIGH SPY DOLL／プラチナリボン",
    ticket: 'https://t-dv.com/yosen_osaka_6',
    image1: 'https://sekigahara-idolwars.net/2026/yosen/osaka/61.jpg',
  },
  {
    cName: 'osaka',
    title: '其の七',
    date: '2026年5月22日（金）',
    open: '18:15',
    start: '18:45',
    place: '大阪・京橋Arc',
    artists:
      "Squall Line／Nody／わんみゅーず！／Lumi Prima／colorin'c／逆転ねこぱんちっ！／tune time capsule／プラチナリボン",
    ticket: 'https://t-dv.com/yosen_osaka_7',
    image1: 'https://sekigahara-idolwars.net/2026/yosen/osaka/71.jpg',
  },
  {
    cName: 'osaka',
    title: '其の八',
    date: '2026年5月24日（日）',
    open: '11:30',
    start: '12:00',
    place: '大阪・京橋Arc',
    artists: "わんみゅーず！／キューハチパーセント！／colorin'c／HIGH SPY DOLL／プラチナリボン",
    ticket: 'https://t-dv.com/yosen_osaka_8',
    image1: 'https://sekigahara-idolwars.net/2026/yosen/osaka/81.jpg',
  },
  {
    cName: 'osaka',
    title: '其の九',
    date: '2026年5月24日（日）',
    open: '17:30',
    start: '18:00',
    place: '大阪・京橋Arc',
    artists:
      "Squall Line／キューハチパーセント！／colorin'c／HIGH SPY DOLL／Mihiro／プラチナリボン",
    ticket: 'https://t-dv.com/yosen_osaka_9',
    image1: 'https://sekigahara-idolwars.net/2026/yosen/osaka/91.jpg',
  },
  {
    cName: 'osaka',
    title: '其の十',
    date: '2026年5月29日（金）',
    open: '18:30',
    start: '18:50',
    place: '大阪・京橋Arc',
    artists: "anemoreel／めろでぃらびっと／Squall Line／わんみゅーず！／colorin'c",
    ticket: 'https://t-dv.com/yosen_osaka_10',
    image1: 'https://sekigahara-idolwars.net/2026/yosen/osaka/101.jpg',
  },
]
