import { YosenAccordionProps } from '@/templates/accordion/YosenAccordion'

export const owariEvents: YosenAccordionProps[] = [
  {
    cName: 'owari',
    title: '其の一',
    date: '2026年5月15日（金）',
    open: '17:30',
    start: '18:00',
    place: 'SOUND SPACE DEEP',
    artists:
      'Harley Queen／夕凪のスピカ／POPING CANDY.／image／Twilight BlooM.／Maycry Liz／逆転ねこぱんちっ！',
    ticket: 'https://t-dv.com/yosen_owari_1',
    image1: 'https://sekigahara-idolwars.net/2026/yosen/owari/11.jpg',
  },
  {
    cName: 'owari',
    title: '其の二',
    date: '2026年5月16日（土）',
    open: '18:00',
    start: '18:30',
    place: '名古屋レジェンドホール',
    artists: 'Yo2La／Harley Queen／IDOL★ST∀R MINE／夕凪のスピカ／POPING CANDY.／AiMEL!!-あいめる-',
    ticket: 'https://t-dv.com/yosen_owari_2',
    image1: 'https://sekigahara-idolwars.net/2026/yosen/owari/21.jpg',
  },
  {
    cName: 'owari',
    title: '其の三',
    date: '2026年5月18日（月）',
    open: '17:00',
    start: '17:30',
    place: '名古屋ReNY',
    artists:
      'Harley Queen／IDOL★ST∀R MINE／夕凪のスピカ／POPING CANDY.／Twilight BlooM.／AiMEL!!-あいめる-／Maycry Liz／逆転ねこぱんちっ！',
    ticket: 'https://t-dv.com/yosen_owari_3',
    image1: 'https://sekigahara-idolwars.net/2026/yosen/owari/31.jpg',
  },
  {
    cName: 'owari',
    title: '其の四',
    date: '2026年5月24日（日）',
    open: '12:00',
    start: '12:30',
    place: 'SOUND SPACE DEEP',
    artists: 'Coloration／Harley Queen／夕凪のスピカ／image／Maycry Liz／逆転ねこぱんちっ！',
    ticket: 'https://t-dv.com/yosen_owari_4',
    image1: 'https://sekigahara-idolwars.net/2026/yosen/owari/41.jpg',
  },
  {
    cName: 'owari',
    title: '其の五',
    date: '2026年5月24日（日）',
    open: '17:30',
    start: '18:00',
    place: 'SOUND SPACE DEEP',
    artists: 'Coloration／夕凪のスピカ／AiMEL!!-あいめる-／Maycry Liz／逆転ねこぱんちっ！',
    ticket: 'https://t-dv.com/yosen_owari_5',
    image1: 'https://sekigahara-idolwars.net/2026/yosen/owari/51.jpg',
  },
  {
    cName: 'owari',
    title: '其の六',
    date: '2026年5月26日（火）',
    open: '18:00',
    start: '18:30',
    place: '名古屋スペードボックス',
    artists:
      'Harley Queen／IDOL★ST∀R MINE／image／AiMEL!!-あいめる-／Maycry Liz／逆転ねこぱんちっ！',
    ticket: 'https://t-dv.com/yosen_owari_6',
    image1: 'https://sekigahara-idolwars.net/2026/yosen/owari/61.jpg',
  },
  {
    cName: 'owari',
    title: '其の七',
    date: '2026年5月27日（水）',
    open: '17:30',
    start: '18:00',
    place: '名古屋スペードボックス',
    artists:
      'Harley Queen／IDOL★ST∀R MINE／POPING CANDY.／image／Twilight BlooM.／AiMEL!!-あいめる-／秘密結社フローリス／逆転ねこぱんちっ！',
    ticket: 'https://t-dv.com/yosen_owari_7',
    image1: 'https://sekigahara-idolwars.net/2026/yosen/owari/71.jpg',
  },
  {
    cName: 'owari',
    title: '其の八',
    date: '2026年5月29日（金）',
    open: '17:30',
    start: '18:00',
    place: 'SOUND SPACE DEEP',
    artists:
      '夕凪のスピカ／POPING CANDY.／image／Twilight BlooM.／AiMEL!!-あいめる-／秘密結社フローリス／逆転ねこぱんちっ！',
    ticket: 'https://t-dv.com/yosen_owari_8',
    image1: 'https://sekigahara-idolwars.net/2026/yosen/owari/81.jpg',
  },
]
