import { ArtistResponseType } from '@/domain/artist'

export const artistsData: ArtistResponseType[] = [
  {
    name: 'iON!',
    x: 'https://x.com/iON_idol_',
    day1: true,
    day2: true,
    day3: null,
    img: 'iON!.JPG',
    read: 'アイオン',
  },
  {
    name: 'EYE CANDY',
    x: 'https://x.com/EYECANDY_idol',
    day1: true,
    day2: null,
    day3: true,
    img: 'EYE CANDY.png',
    read: 'アイキャンディー',
  },
  {
    name: 'i-COL',
    x: 'https://x.com/icol_official',
    day1: null,
    day2: true,
    day3: null,
    img: 'i-COL.jpg',
    read: 'アイコル',
  },
  {
    name: 'アイドルカレッジ',
    x: 'https://x.com/ic_idolcollege',
    day1: null,
    day2: true,
    day3: true,
    img: '%E3%82%A2%E3%82%A4%E3%83%88%E3%82%99%E3%83%AB%E3%82%AB%E3%83%AC%E3%83%83%E3%82%B7%E3%82%99.jpg',
    read: 'アイドルコレクション',
  },
  {
    name: 'IDOLEST',
    x: 'https://x.com/tokyoidolest',
    day1: true,
    day2: true,
    day3: null,
    img: 'IDOLEST.jpeg',
    read: 'アイドレスト',
  },
  {
    name: 'I MY ME MINE',
    x: 'https://x.com/IMMM_official',
    day1: null,
    day2: true,
    day3: true,
    img: 'I MY ME MINE.png',
    read: 'アイマイミーマイン',
  },
  {
    name: 'iLiFE!',
    x: 'https://x.com/iLiFE_official',
    day1: true,
    day2: null,
    day3: null,
    img: 'iLiFE!.jpg',
    read: 'アイライフ',
  },
  {
    name: 'あおぞらをキミに',
    x: 'https://x.com/aozorawokimini',
    day1: null,
    day2: true,
    day3: true,
    img: '%E3%81%82%E3%81%8A%E3%81%9E%E3%82%89%E3%82%92%E3%82%AD%E3%83%9F%E3%81%AB.png',
    read: 'アオゾラヲキミニ',
  },
  {
    name: 'アキシブproject',
    x: 'https://x.com/AkishibuProject',
    day1: true,
    day2: true,
    day3: null,
    img: 'アキシブproject.jpg',
    read: 'アキシブプロジェクト',
  },
  {
    name: 'AQA',
    x: 'https://x.com/AQA_info',
    day1: null,
    day2: null,
    day3: true,
    img: 'AQA.jpg',
    read: 'アクア',
  },
  {
    name: 'あくまで天使',
    x: 'https://x.com/akuten_info',
    day1: null,
    day2: true,
    day3: null,
    img: 'あくまで天使.JPG',
    read: 'アクマデテンシ',
  },
  {
    name: 'As a Cutie Pomeranian',
    x: 'https://x.com/aacp_official',
    day1: null,
    day2: true,
    day3: true,
    img: 'As a Cutie Pomeranian.jpg',
    read: 'アズアキューティーポメラニアン',
  },
  {
    name: 'アステリア',
    x: 'https://x.com/Asteria_group',
    day1: null,
    day2: true,
    day3: null,
    img: 'アステリア.jpg',
    read: 'アステリア',
  },
  {
    name: 'AdamLilith',
    x: 'https://x.com/Adamth_official',
    day1: null,
    day2: true,
    day3: true,
    img: 'AdamLilith.JPG',
    read: 'アダムリリス',
  },
  {
    name: 'アップアップガールズ（２）',
    x: 'https://x.com/uug2official',
    day1: null,
    day2: null,
    day3: true,
    img: 'アップアップガールズ(２).jpeg',
    read: 'アップアップガールズ（カッコニ）',
  },
  {
    name: '雨のち、ハレーション',
    x: 'https://x.com/AMEHAREOfficial',
    day1: true,
    day2: null,
    day3: null,
    img: '雨のち、ハレーション.jpg',
    read: 'アメノチ、ハレーション',
  },
  {
    name: 'Alcute！',
    x: 'https://x.com/alcute_official',
    day1: true,
    day2: null,
    day3: null,
    img: 'Alcute！.jpg',
    read: 'アルキュート',
  },
  {
    name: 'アルテミスの翼',
    x: 'https://x.com/artemis_idol7',
    day1: true,
    day2: true,
    day3: null,
    img: 'アルテミスの翼.jpeg',
    read: 'アルテミスノツバサ',
  },
  {
    name: 'α',
    x: 'https://x.com/alpha_info_',
    day1: true,
    day2: null,
    day3: null,
    img: 'α.jpg',
    read: 'アルファ',
  },
  {
    name: 'いざ参らん',
    x: 'https://x.com/izamairan2023',
    day1: true,
    day2: null,
    day3: null,
    img: 'いざ参らん.jpeg',
    read: 'イザマイラン',
  },
  {
    name: 'Ill',
    x: 'https://x.com/Ill_Idol',
    day1: null,
    day2: null,
    day3: true,
    img: 'Ill.jpg',
    read: 'イル',
  },
  {
    name: '泡沫パーティーズ',
    x: 'https://x.com/utapa_official',
    day1: true,
    day2: null,
    day3: null,
    img: '泡沫パーティーズ.png',
    read: 'ウタカタパーティーズ',
  },
  {
    name: 'UtaGe!',
    x: 'https://x.com/info_UtaGe',
    day1: true,
    day2: null,
    day3: null,
    img: 'UtaGe!.jpg',
    read: 'ウタゲ',
  },
  {
    name: 'ESTLINK☆',
    x: 'https://x.com/estlink2021',
    day1: null,
    day2: null,
    day3: true,
    img: 'ESTLINK☆.jpeg',
    read: 'エストリンクスター',
  },
  {
    name: 'エラバレシ',
    x: 'https://x.com/_erabareshi_',
    day1: null,
    day2: null,
    day3: true,
    img: 'エラバレシ.jpg',
    read: 'エラバレシ',
  },
  {
    name: 'ゑんら',
    x: 'https://x.com/wyenra',
    day1: true,
    day2: null,
    day3: null,
    img: '%E3%82%91%E3%82%93%E3%82%89.HEIC',
    read: 'エンラ',
  },
  {
    name: 'OS☆U',
    x: 'https://x.com/osuofficial',
    day1: null,
    day2: null,
    day3: true,
    img: 'OS☆U.png',
    read: 'オーエスユー',
  },
  {
    name: 'Ｏ₂',
    x: 'https://x.com/o2_429official',
    day1: null,
    day2: null,
    day3: true,
    img: 'Ｏ₂.png',
    read: 'オーツー',
  },
  {
    name: 'オカシリゾート',
    x: 'https://x.com/okashi_staff',
    day1: null,
    day2: true,
    day3: null,
    img: 'オカシリゾート.png',
    read: 'オカシリゾート',
  },
  {
    name: 'KAIJU ON THE STAGE',
    x: 'https://x.com/kaiju_staff',
    day1: null,
    day2: true,
    day3: null,
    img: 'KAIJU ON THE STAGE.png',
    read: 'カイジュウオンザステージ',
  },
  {
    name: '仮面女子',
    x: 'https://x.com/AliceProject_mb',
    day1: null,
    day2: true,
    day3: null,
    img: '仮面女子.jpg',
    read: 'カメンジョシ',
  },
  {
    name: 'カラフルスクリーム',
    x: 'https://x.com/colorful_scream',
    day1: null,
    day2: true,
    day3: true,
    img: 'カラフルスクリーム.jpg',
    read: 'カラフルスクリーム',
  },
  {
    name: 'カリスマめんざいふっ！',
    x: 'https://x.com/KariMen_idol',
    day1: true,
    day2: true,
    day3: null,
    img: 'カリスマめんざいふっ！.jpeg',
    read: 'カリスマメンザイフッ！',
  },
  {
    name: '可憐なアイボリー',
    x: 'https://x.com/karennaivory',
    day1: null,
    day2: true,
    day3: true,
    img: '%E5%8F%AF%E6%86%90%E3%81%AA%E3%82%A2%E3%82%A4%E3%83%9B%E3%82%99%E3%83%AA%E3%83%BC.jpg',
    read: 'カレンナアイボリー',
  },
  {
    name: '君に、胸キュン。',
    x: 'https://x.com/kimikyun_office',
    day1: null,
    day2: true,
    day3: true,
    img: '君に、胸キュン。.png',
    read: 'キミニ、ムネキュン。',
  },
  {
    name: 'キミニハネ',
    x: 'https://x.com/kiminihane_info',
    day1: null,
    day2: true,
    day3: null,
    img: 'キミニハネ.jpg',
    read: 'キミニハネ',
  },
  {
    name: '逆転ねこぱんちっ！',
    x: 'https://x.com/tenneko_NAGOYA',
    day1: true,
    day2: null,
    day3: null,
    img: '逆転ねこぱんちっ！.png',
    read: 'ギャクテンネコパンチッ！',
  },
  {
    name: 'CAL&RES',
    x: 'https://x.com/calresofficial',
    day1: null,
    day2: true,
    day3: true,
    img: 'CAL&RES.JPG',
    read: 'キャルアンドレス',
  },
  {
    name: 'Qu♡Aly',
    x: 'https://x.com/qualy_info',
    day1: null,
    day2: true,
    day3: true,
    img: 'Qu♡Aly.jpeg',
    read: 'キュアリー',
  },
  {
    name: 'きゅ～くる',
    x: 'https://x.com/cu_clu',
    day1: null,
    day2: null,
    day3: true,
    img: 'きゅ～くる.jpg',
    read: 'キュークル',
  },
  {
    name: '九州女子翼',
    x: 'https://x.com/ITR_KGW',
    day1: null,
    day2: true,
    day3: true,
    img: '九州女子翼.JPG',
    read: 'キュウシュウジョシリュウ',
  },
  {
    name: 'キュン!?恋堕ちキューピッド',
    x: 'https://x.com/qpid_info',
    day1: true,
    day2: null,
    day3: null,
    img: '%E3%82%AD%E3%83%A5%E3%83%B3%21_%E6%81%8B%E5%A0%95%E3%81%A1%E3%82%AD%E3%83%A5%E3%83%BC%E3%83%94%E3%83%83%E3%83%89.jpg',
    read: 'キュン!?コイオチキューピッド',
  },
  {
    name: '煌めき☆アンフォレント',
    x: 'https://x.com/kirafore_info',
    day1: null,
    day2: true,
    day3: true,
    img: '煌めき☆アンフォレント.jpg',
    read: 'キラメキ☆アンフォレント',
  },
  {
    name: 'GILTY×GILTY',
    x: 'https://x.com/GILTYxGILTY',
    day1: null,
    day2: true,
    day3: null,
    img: 'GILTY×GILTY.jpg',
    read: 'ギルティーギルティー',
  },
  {
    name: 'Glim Assembler',
    x: 'https://x.com/Glimas_info',
    day1: true,
    day2: true,
    day3: null,
    img: 'Glim Assembler.png',
    read: 'グリムアセンブラー',
  },
  {
    name: 'KRD8',
    x: 'https://x.com/KRD_08',
    day1: null,
    day2: true,
    day3: true,
    img: 'KRD8.jpg',
    read: 'ケーアールディーエイト',
  },
  {
    name: 'KOIHAJI ',
    x: 'https://x.com/KOIHAJI_idol',
    day1: null,
    day2: true,
    day3: true,
    img: 'KOIHAJI.jpg',
    read: 'コイハジ',
  },
  {
    name: 'SAI ²Rium',
    x: 'https://x.com/sai2rium',
    day1: true,
    day2: null,
    day3: null,
    img: 'SAI ²Rium.jpg',
    read: 'サイサイリウム',
  },
  {
    name: 'サクヤコノハナ',
    x: 'https://x.com/SKKH_official',
    day1: null,
    day2: true,
    day3: true,
    img: 'サクヤコノハナ.jpg',
    read: 'サクヤコノハナ',
  },
  {
    name: 'THE ENCORE',
    x: 'https://x.com/TheEncore_info',
    day1: null,
    day2: true,
    day3: true,
    img: 'THE ENCORE.jpg',
    read: 'ジアンコール',
  },
  {
    name: 'シークレットシャノワール',
    x: 'https://x.com/secretchatnoir',
    day1: true,
    day2: true,
    day3: true,
    img: 'シークレットシャノワール.jpg',
    read: 'シークレットシャノワール',
  },
  {
    name: 'ジエメイ',
    x: 'https://x.com/jiemei_idol',
    day1: null,
    day2: null,
    day3: true,
    img: 'ジエメイ.jpg',
    read: 'ジエメイ',
  },
  {
    name: 'JAPANARIZM',
    x: 'https://x.com/JAPANARIZM_info',
    day1: null,
    day2: true,
    day3: true,
    img: 'JAPANARIZM.jpg',
    read: 'ジャパナリズム',
  },
  {
    name: 'JamsCollection',
    x: 'https://x.com/JamsCollection',
    day1: null,
    day2: true,
    day3: true,
    img: 'JamsCollection.jpg',
    read: 'ジャムズコレクション',
  },
  {
    name: '終末のアンセム',
    x: 'https://x.com/owathem',
    day1: true,
    day2: null,
    day3: null,
    img: '終末のアンセム.png',
    read: 'シュウマツノアンセム',
  },
  {
    name: 'Jewel☆Garden',
    x: 'https://x.com/_JewelGarden_',
    day1: null,
    day2: true,
    day3: null,
    img: 'Jewel☆Garden.jpg',
    read: 'ジュエルガーデン',
  },
  {
    name: 'シュレーディンガーの犬',
    x: 'https://x.com/schro_official',
    day1: true,
    day2: null,
    day3: null,
    img: '%E3%82%B7%E3%83%A5%E3%83%AC%E3%83%BC%E3%83%86%E3%82%99%E3%82%A3%E3%83%B3%E3%82%AB%E3%82%99%E3%83%BC%E3%81%AE%E7%8A%AC.jpg',
    read: 'シュレーディンガーノイヌ',
  },
  {
    name: 'シンデレラ宣言！',
    x: 'https://x.com/cinsen_official',
    day1: true,
    day2: true,
    day3: null,
    img: '%E3%82%B7%E3%83%B3%E3%83%86%E3%82%99%E3%83%AC%E3%83%A9%E5%AE%A3%E8%A8%80%EF%BC%81.jpg',
    read: 'シンデレラセンゲン！',
  },
  {
    name: 'Sweet Alley',
    x: 'https://x.com/SweetAlley_info',
    day1: null,
    day2: true,
    day3: true,
    img: 'Sweet Alley.jpg',
    read: 'スウィートアレイ',
  },
  {
    name: 'SUPER☆GiRLS',
    x: 'https://x.com/SUPERGiRLS_AMG',
    day1: null,
    day2: null,
    day3: true,
    img: 'SUPER☆GiRLS.jpeg',
    read: 'スーパーガールズ',
  },
  {
    name: 'すーぱーぷーばぁー!!',
    x: 'https://x.com/_superpouvoir',
    day1: null,
    day2: true,
    day3: true,
    img: '%E3%81%99%E3%83%BC%E3%81%B1%E3%83%BC%E3%81%B7%E3%83%BC%E3%81%B0%E3%81%81%E3%83%BC%E2%80%BC.jpg',
    read: 'スーパープーバー!!',
  },
  {
    name: 'ZUTTOMOTTO',
    x: 'https://x.com/zuttomoofficial',
    day1: null,
    day2: true,
    day3: true,
    img: 'ZUTTOMOTTO.jpg',
    read: 'ズットモット',
  },
  {
    name: 'STELLASTELLA',
    x: 'https://x.com/STESTE_official',
    day1: true,
    day2: true,
    day3: null,
    img: 'STELLASTELLA.jpg',
    read: 'ステラステラ',
  },
  {
    name: 'SPRISE',
    x: 'https://x.com/sprise_official',
    day1: true,
    day2: null,
    day3: null,
    img: 'SPRISE.jpg',
    read: 'スプライズ',
  },
  {
    name: 'スポポポポニー',
    x: 'https://x.com/Spopopopony',
    day1: true,
    day2: true,
    day3: true,
    img: 'スポポポポニー.jpg',
    read: 'スポポポポニー',
  },
  {
    name: 'SAY-LA',
    x: 'https://x.com/SAY_LA_info',
    day1: true,
    day2: true,
    day3: null,
    img: 'SAY-LA.jpg',
    read: 'セイラ',
  },
  {
    name: '世界逆転宣言！',
    x: 'https://x.com/sekai_gyakuten',
    day1: null,
    day2: true,
    day3: true,
    img: '世界逆転宣言！.jpg',
    read: 'セカイギャクテンセンゲン',
  },
  {
    name: 'セカモノ',
    x: 'https://x.com/sekamono',
    day1: true,
    day2: true,
    day3: null,
    img: 'セカモノ.jpeg',
    read: 'セカモノ',
  },
  {
    name: 'SAISON',
    x: 'https://x.com/saison_idol',
    day1: true,
    day2: null,
    day3: null,
    img: 'SAISON.jpg',
    read: 'セゾン',
  },
  {
    name: 'ゼロキョリハーツ',
    x: 'https://x.com/ZKH_official',
    day1: true,
    day2: null,
    day3: null,
    img: 'ゼロキョリハーツ.jpeg',
    read: 'ゼロキョリハーツ',
  },
  {
    name: 'Cent Heaven',
    x: 'https://x.com/CentH_official',
    day1: null,
    day2: null,
    day3: true,
    img: 'Cent Heaven.jpg',
    read: 'セントヘブン',
  },
  {
    name: 'Task have Fun',
    x: 'https://x.com/TaskhaveFun_ST',
    day1: true,
    day2: true,
    day3: null,
    img: 'Task have Fun.jpg',
    read: 'タスクハブファン',
  },
  {
    name: 'WT★Egret',
    x: 'https://x.com/wt_egret',
    day1: null,
    day2: null,
    day3: true,
    img: 'WT_Egret.jpg',
    read: 'ダブリューティー★イーグレット',
  },
  {
    name: 'W.ダブルヴィー',
    x: 'https://x.com/w__official',
    day1: true,
    day2: true,
    day3: null,
    img: 'W.%E3%82%BF%E3%82%99%E3%83%95%E3%82%99%E3%83%AB%E3%82%A6%E3%82%99%E3%82%A3%E3%83%BC.png',
    read: 'ダブルヴィー',
  },
  {
    name: 'ちあもあ！',
    x: 'https://x.com/Tiamoa_',
    day1: true,
    day2: null,
    day3: null,
    img: 'ちあもあ.png',
    read: 'チアモア',
  },
  {
    name: 'チキータ',
    x: 'https://x.com/Chegattz',
    day1: true,
    day2: null,
    day3: null,
    img: 'チキータ.png',
    read: 'チキータ',
  },
  {
    name: '月に足跡を残した少女達は一体何を見たのか...',
    x: 'https://x.com/tsukiato_staff',
    day1: null,
    day2: null,
    day3: true,
    img: '月に足跡を残した少女達は一体何を見たのか.jpg',
    read: 'ツキニアシアトヲノコシタショウジョタチハイッタイナニヲミタノカ...',
  },
  {
    name: 'ティラミス',
    x: 'https://x.com/tiramis_staff',
    day1: true,
    day2: null,
    day3: null,
    img: 'ティラミス.jpeg',
    read: 'ティラミス',
  },
  {
    name: '手羽先センセーション',
    x: 'https://x.com/tebasen_info',
    day1: null,
    day2: true,
    day3: true,
    img: '手羽先センセーション.jpg',
    read: 'テバサキセンセーション',
  },
  {
    name: 'dela',
    x: 'https://x.com/dela_nbgf',
    day1: null,
    day2: null,
    day3: true,
    img: 'dela.jpeg',
    read: 'デラ',
  },
  {
    name: 'テラテラ',
    x: 'https://x.com/teratera_staff',
    day1: null,
    day2: true,
    day3: null,
    img: 'テラテラ.jpg',
    read: 'テラテラ',
  },
  {
    name: '天空のシラバス',
    x: 'https://x.com/skysyllabus',
    day1: null,
    day2: null,
    day3: true,
    img: '天空のシラバス.jpg',
    read: 'テンクウノシラバス',
  },
  {
    name: 'テンシンランマン',
    x: 'https://x.com/tenran_official',
    day1: true,
    day2: true,
    day3: null,
    img: 'テンシンランマン.JPG',
    read: 'テンシンランマン',
  },
  {
    name: '点染テンセイ少女。',
    x: 'https://x.com/tenten_info',
    day1: null,
    day2: true,
    day3: true,
    img: '点染テンセイ少女。.jpg',
    read: 'テンセンテンセイショウジョ',
  },
  {
    name: 'TENRIN',
    x: 'https://x.com/TENRIN_official',
    day1: null,
    day2: true,
    day3: true,
    img: 'TENRIN.jpg',
    read: 'テンリン',
  },
  {
    name: 'Drug&Drop',
    x: 'https://x.com/DrugDrop_info',
    day1: true,
    day2: true,
    day3: null,
    img: 'Drug&Drop.jpg',
    read: 'ドラッグアンドドロップ',
  },
  {
    name: 'DREAMING MONSTER',
    x: 'https://x.com/tpotona',
    day1: true,
    day2: true,
    day3: null,
    img: 'DREAMING MONSTER.jpg',
    read: 'ドリーミングモンスター',
  },
  {
    name: 'ドレスコード',
    x: 'https://x.com/dreco_info',
    day1: null,
    day2: true,
    day3: true,
    img: 'ドレスコード.jpg',
    read: 'ドレスコード',
  },
  {
    name: '夏空のオリオン',
    x: 'https://x.com/natsuori_info',
    day1: null,
    day2: true,
    day3: true,
    img: '夏空のオリオン.png',
    read: 'ナツゾラノオリオン',
  },
  {
    name: 'ナト☆カン',
    x: 'https://x.com/NATOKAAAN',
    day1: null,
    day2: true,
    day3: null,
    img: 'ナト☆カン.jpg',
    read: 'ナト☆カン',
  },
  {
    name: 'なないろ∞ミルキーウェイ',
    x: 'https://x.com/7__Milkyway',
    day1: null,
    day2: true,
    day3: true,
    img: 'なないろ∞ミルキーウェイ.jpeg',
    read: 'ナナイロムゲンミルキーウェイ',
  },
  {
    name: 'ナナコロビヤオキ',
    x: 'https://x.com/nanakoro_info',
    day1: true,
    day2: true,
    day3: null,
    img: 'ナナコロビヤオキ.jpeg',
    read: 'ナナコロビヤオキ',
  },
  {
    name: 'なみだ色の消しごむ',
    x: 'https://x.com/namikeshi_info',
    day1: true,
    day2: true,
    day3: null,
    img: '%E3%81%AA%E3%81%BF%E3%81%A0%E8%89%B2%E3%81%AE%E6%B6%88%E3%81%97%E3%81%94%E3%82%80.jpg',
    read: 'ナミダイロノケシゴム',
  },
  {
    name: '虹色の飛行少女',
    x: 'https://x.com/nijihikoushojo',
    day1: null,
    day2: true,
    day3: true,
    img: '虹色の飛行少女.jpg',
    read: 'ニジイロノヒコウショウジョ',
  },
  {
    name: 'にっぽんワチャチャ',
    x: 'https://x.com/nippon_wachacha',
    day1: null,
    day2: null,
    day3: true,
    img: 'にっぽんワチャチャ.png',
    read: 'ニッポンワチャチャ',
  },
  {
    name: 'NEO BREAK',
    x: 'https://x.com/NEOBREAK_info',
    day1: null,
    day2: true,
    day3: true,
    img: 'NEO BREAK.jpeg',
    read: 'ネオブレイク',
  },
  {
    name: '脳内パステル',
    x: 'https://x.com/Nopas_Official',
    day1: null,
    day2: true,
    day3: true,
    img: '脳内パステル.png',
    read: 'ノウナイパステル',
  },
  {
    name: 'ノルニル',
    x: 'https://x.com/nornir_0611',
    day1: true,
    day2: true,
    day3: null,
    img: 'ノルニル.jpeg',
    read: 'ノルニル',
  },
  {
    name: 'のんふぃく！',
    x: 'https://x.com/nonfic_official',
    day1: true,
    day2: true,
    day3: null,
    img: 'のんふぃく！.jpg',
    read: 'ノンフィク！',
  },
  {
    name: 'HIGH SPIRITS',
    x: 'https://x.com/HiSp_info',
    day1: null,
    day2: true,
    day3: true,
    img: 'HIGH SPIRITS.jpg',
    read: 'ハイスピリッツ',
  },
  {
    name: 'はいどーも！テラスマです！',
    x: 'https://x.com/TeraSmile1',
    day1: null,
    day2: true,
    day3: true,
    img: 'テラスマ.png',
    read: 'ハイドーモ',
  },
  {
    name: '蜂蜜★皇帝',
    x: 'https://x.com/hachipera',
    day1: true,
    day2: null,
    day3: null,
    img: '蜂蜜★皇帝.png',
    read: 'ハチミツコウテイ',
  },
  {
    name: 'HAPPY CREATORS',
    x: 'https://x.com/hpcr__official',
    day1: null,
    day2: null,
    day3: true,
    img: 'HAPPY CREATORS.jpg',
    read: 'ハッピークリエイターズ',
  },
  {
    name: '花いろは',
    x: 'https://x.com/hanairoha_ww',
    day1: true,
    day2: true,
    day3: true,
    img: '花いろは.jpg',
    read: 'ハナイロハ',
  },
  {
    name: 'ハニースパイスRe.',
    x: 'https://x.com/honeyspice_re',
    day1: true,
    day2: true,
    day3: null,
    img: '%E3%83%8F%E3%83%8B%E3%83%BC%E3%82%B9%E3%83%8F%E3%82%9A%E3%82%A4%E3%82%B9Re.png',
    read: 'ハニースパイスアールイー',
  },
  {
    name: 'Bunny La Crew',
    x: 'https://x.com/BunnyLaCrew',
    day1: true,
    day2: null,
    day3: null,
    img: 'Bunny La Crew.jpg',
    read: 'バニーラクルー',
  },
  {
    name: 'Panic Monster !n Wonderland',
    x: 'https://x.com/pmiw_info',
    day1: true,
    day2: true,
    day3: null,
    img: 'Panic Monster !n Wonderland.JPG',
    read: 'パニックモンスターインワンダーランド',
  },
  {
    name: 'パラディーク',
    x: 'https://x.com/para_deeq',
    day1: null,
    day2: null,
    day3: true,
    img: 'パラディーク.JPG',
    read: 'パラディーク',
  },
  {
    name: 'パラレルサイダー',
    x: 'https://x.com/parasai_info',
    day1: null,
    day2: true,
    day3: true,
    img: 'パラレルサイダー.jpg',
    read: 'パラレルサイダー',
  },
  {
    name: "parfait d'ange",
    x: 'https://x.com/info_parfait',
    day1: true,
    day2: true,
    day3: true,
    img: 'parfait d_ange.jpg',
    read: 'パルフェダンジュ',
  },
  {
    name: 'Palette Parade',
    x: 'https://x.com/O_PaletteParade',
    day1: null,
    day2: true,
    day3: true,
    img: 'Palette Parade.jpg',
    read: 'パレットパレード',
  },
  {
    name: 'ハレとハレ！',
    x: 'https://x.com/_HARETOHARE',
    day1: null,
    day2: null,
    day3: true,
    img: 'ハレとハレ！.jpeg',
    read: 'ハレトハレ！',
  },
  {
    name: 'ビーバイユー',
    x: 'https://x.com/bebyu_official',
    day1: true,
    day2: true,
    day3: true,
    img: 'ビーバイユー.jpg',
    read: 'ビーバイユー',
  },
  {
    name: 'Peel the Apple',
    x: 'https://x.com/PtA_staff',
    day1: null,
    day2: true,
    day3: true,
    img: 'Peel the Apple.jpg',
    read: 'ピールジアップル',
  },
  {
    name: 'ひとつキラリ',
    x: 'https://x.com/hitotsukirari',
    day1: true,
    day2: null,
    day3: null,
    img: 'ひとつキラリ.jpeg',
    read: 'ヒトツキラリ',
  },
  {
    name: 'FES☆TIVE',
    x: 'https://x.com/FESTIVEofficial',
    day1: true,
    day2: true,
    day3: true,
    img: 'FES☆TIVE.jpg',
    read: 'フェス☆ティブ',
  },
  {
    name: 'プエラの絶対値',
    x: 'https://x.com/Puella_official',
    day1: null,
    day2: true,
    day3: null,
    img: '%E3%83%97%E3%82%A8%E3%83%A9%E3%81%AE%E7%B5%B6%E5%AF%BE%E5%80%A4.jpeg',
    read: 'プエラノゼッタイチ',
  },
  {
    name: 'フューチャーサイダー',
    x: 'https://x.com/chaider_info',
    day1: true,
    day2: true,
    day3: null,
    img: 'フューチャーサイダー.jpg',
    read: 'フューチャーサイダー',
  },
  {
    name: 'ぷりしえーる',
    x: 'https://x.com/Pricie_official',
    day1: null,
    day2: null,
    day3: true,
    img: 'ぷりしえーる.JPG',
    read: 'プリシエール',
  },
  {
    name: 'PrincessGarden-TOKYO-',
    x: 'https://x.com/_PrincessGarden',
    day1: true,
    day2: true,
    day3: null,
    img: 'PrincessGarden-TOKYO-.jpg',
    read: 'プリンセスガーデントーキョー',
  },
  {
    name: 'フルーティー',
    x: 'https://x.com/fruity_lp',
    day1: true,
    day2: true,
    day3: null,
    img: 'フルーティー.jpg',
    read: 'フルーティー',
  },
  {
    name: 'ぺりきゅらむ',
    x: 'https://x.com/info_periculum',
    day1: null,
    day2: null,
    day3: true,
    img: 'ぺりきゅらむ.png',
    read: 'ペリキュラム',
  },
  {
    name: 'ベンジャス！',
    x: 'https://x.com/benjas_official',
    day1: true,
    day2: null,
    day3: null,
    img: 'ベンジャス！.png',
    read: 'ベンジャス！',
  },
  {
    name: 'HOT DOG CAT',
    x: 'https://x.com/HOTDOGCAT_info',
    day1: true,
    day2: true,
    day3: null,
    img: 'HOT DOG CAT.jpg',
    read: 'ホットドッグキャット',
  },
  {
    name: "Poppin' Parade",
    x: 'https://x.com/official_popipa',
    day1: true,
    day2: true,
    day3: null,
    img: 'Poppin_%20Parade.jpg',
    read: 'ポッピンパレード',
  },
  {
    name: 'ポラライト',
    x: 'https://x.com/polalight_info',
    day1: null,
    day2: true,
    day3: true,
    img: 'ポラライト.jpg',
    read: 'ポラライト',
  },
  {
    name: 'ポンコツコンポ',
    x: 'https://x.com/ponkotsukonpo',
    day1: true,
    day2: true,
    day3: null,
    img: 'ポンコツコンポ.JPG',
    read: 'ポンコツコンポ',
  },
  {
    name: 'My_Stage',
    x: 'https://x.com/My_Stage_',
    day1: true,
    day2: true,
    day3: null,
    img: 'My_Stage.jpg',
    read: 'マイステージ',
  },
  {
    name: 'MyDearDarlin’',
    x: 'https://x.com/MyDear_official',
    day1: null,
    day2: true,
    day3: true,
    img: 'MyDearDarlin’.JPEG',
    read: 'マイディアダーリン',
  },
  {
    name: 'MyDresscode',
    x: 'https://x.com/_MyDresscode_',
    day1: true,
    day2: true,
    day3: null,
    img: 'MyDresscode.png',
    read: 'マイドレスコード',
  },
  {
    name: "Ma'Scar'Piece",
    x: 'https://x.com/mascarpiece',
    day1: true,
    day2: true,
    day3: null,
    img: 'Ma_Scar_Piece.jpg',
    read: 'マスカーピース',
  },
  {
    name: 'MATANAGOYA',
    x: 'https://x.com/matanagoya',
    day1: true,
    day2: null,
    day3: null,
    img: 'MATANAGOYA.jpg',
    read: 'マタナゴヤ',
  },
  {
    name: 'まねきケチャ',
    x: 'https://x.com/maneki_kecak',
    day1: true,
    day2: true,
    day3: null,
    img: 'まねきケチャ.jpg',
    read: 'マネキケチャ',
  },
  {
    name: '蜜兎',
    x: 'https://x.com/HNBN_official',
    day1: null,
    day2: true,
    day3: true,
    img: '蜜兎.png',
    read: 'ミツウサギ',
  },
  {
    name: 'みらくらんど',
    x: 'https://x.com/MCL39_official',
    day1: null,
    day2: null,
    day3: true,
    img: 'みらくらんど.png',
    read: 'ミラクランド',
  },
  {
    name: 'Milky＊Sphene',
    x: 'https://x.com/MilkySphene',
    day1: true,
    day2: true,
    day3: true,
    img: 'Milky＊Sphene.jpg',
    read: 'ミルキースフィーン',
  },
  {
    name: 'メイビーME',
    x: 'https://x.com/MAYBEME0707',
    day1: true,
    day2: true,
    day3: null,
    img: 'メイビーME.png',
    read: 'メイビーミー',
  },
  {
    name: 'MEGAFON',
    x: 'https://x.com/MEGAFON_idol',
    day1: true,
    day2: true,
    day3: null,
    img: 'MEGAFON.jpg',
    read: 'メガフォン',
  },
  {
    name: 'Melty BeaR',
    x: 'https://x.com/melty_bear_',
    day1: null,
    day2: true,
    day3: true,
    img: 'Melty BeaR.png',
    read: 'メルティベア',
  },
  {
    name: 'Y∀KiN',
    x: 'https://x.com/YAKiN_0209',
    day1: true,
    day2: true,
    day3: null,
    img: 'Y∀KiN.png',
    read: 'ヤキン',
  },
  {
    name: '夜光性アミューズ',
    x: 'https://x.com/Yoruamiofficial',
    day1: true,
    day2: true,
    day3: null,
    img: '%E5%A4%9C%E5%85%89%E6%80%A7%E3%82%A2%E3%83%9F%E3%83%A5%E3%83%BC%E3%82%B9%E3%82%99.jpg',
    read: 'ヤコウセイアミューズ',
  },
  {
    name: '夜宙☆ShiNew’',
    x: 'https://x.com/star_shinew',
    day1: null,
    day2: null,
    day3: true,
    img: '夜宙☆ShiNew’.jpg',
    read: 'ヤチュウシャイニュー',
  },
  {
    name: 'ヤンチャン学園音楽部',
    x: 'https://x.com/YGakuenmember',
    day1: true,
    day2: true,
    day3: null,
    img: 'ヤンチャン学園音楽部.jpg',
    read: 'ヤンチャンガクオンガクブ',
  },
  {
    name: 'ゆるめるモ！',
    x: 'https://x.com/ylmlm_official',
    day1: null,
    day2: true,
    day3: null,
    img: 'ゆるめるモ！.jpg',
    read: 'ユルメルモ',
  },
  {
    name: 'ラビットビット',
    x: 'https://x.com/rabbitbit2022',
    day1: null,
    day2: true,
    day3: null,
    img: 'ラビットビット.jpg',
    read: 'ラビットビット',
  },
  {
    name: 'LOVEME',
    x: 'https://x.com/LOVEME_idol',
    day1: true,
    day2: null,
    day3: null,
    img: 'LOVEME.jpg',
    read: 'ラブミー',
  },
  {
    name: 'Re:Clash',
    x: 'https://x.com/reclash0922',
    day1: null,
    day2: null,
    day3: true,
    img: 'リークラ.png',
    read: 'リクラッシュ',
  },
  {
    name: 'Lily wonder',
    x: 'https://x.com/LW___official',
    day1: true,
    day2: true,
    day3: true,
    img: 'Lily wonder.jpg',
    read: 'リリーワンダー',
  },
  {
    name: 'RiNCENT#',
    x: 'https://x.com/rincent_idol',
    day1: null,
    day2: true,
    day3: true,
    img: 'RiNCENT%E2%99%AF.JPG',
    read: 'リンセントシャープ',
  },
  {
    name: 'Luce Twinkle Wink☆',
    x: 'https://x.com/Luce_TW',
    day1: null,
    day2: true,
    day3: true,
    img: 'Luce Twinkle Wink☆.jpeg',
    read: 'ルーチェトゥインクルウィンク',
  },
  {
    name: 'Root mimi',
    x: 'https://x.com/Root__mimi',
    day1: true,
    day2: null,
    day3: null,
    img: 'Root mimi.jpg',
    read: 'ルートミミ',
  },
  {
    name: 'Loulouchouchou',
    x: 'https://x.com/Llcc_info',
    day1: true,
    day2: null,
    day3: null,
    img: 'Loulouchouchou.jpg',
    read: 'ルルシュシュシュ',
  },
  {
    name: 'READY TO KISS',
    x: 'https://x.com/READYTOKISSoffi',
    day1: true,
    day2: true,
    day3: null,
    img: 'READY TO KISS.jpg',
    read: 'レディートゥキス',
  },
  {
    name: 'LADYBABY',
    x: 'https://x.com/LADYBABY_JP',
    day1: null,
    day2: true,
    day3: true,
    img: 'LADYBABY.jpg',
    read: 'レディベイビー',
  },
  {
    name: 'Lollipop♡CHU',
    x: 'https://x.com/Lollipop__CHU',
    day1: true,
    day2: true,
    day3: true,
    img: 'Lollipop♡CHU.jpg',
    read: 'ロリポップチュウ',
  },
  {
    name: 'わーすた',
    x: 'https://x.com/tws_staff',
    day1: null,
    day2: null,
    day3: true,
    img: 'わーすた.jpg',
    read: 'ワースタ',
  },
  {
    name: 'われらがプワプワプーワプワ',
    x: 'https://x.com/puwapuwapu_wa',
    day1: true,
    day2: true,
    day3: null,
    img: 'われらがプワプワプーワプワ.jpeg',
    read: 'ワレラガプワプワプーワプワ',
  },
  {
    name: 'ワンダーウィード 天',
    x: 'https://x.com/wonder__weed',
    day1: true,
    day2: true,
    day3: true,
    img: 'ワンダーウィード 天.jpg',
    read: 'ワンダーウィード テン',
  },
  {
    name: 'わんふぁす！',
    x: 'https://x.com/WONFAS_official',
    day1: true,
    day2: null,
    day3: null,
    img: 'わんふぁす！.JPG',
    read: 'ワンファス！',
  },
]
